language: node_js

node_js:
  - "stable"

before_script:
  - "npm i -g gatsby-cli"
  - "npm i"

script:
  - "npm run test"
  - "npm run build"

after_success:
  - chmod +x ./scripts/lighthouse.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./scripts/lighthouse.sh ; fi'
